---
title: "Instrumental variables"
author: "Pablo Geraldo Bastías"
logo: "https://fundit.fr/sites/default/files/styles/max_650x650/public/institutions/capture-decran-2023-07-07-162216.png?itok=1CkwlJEu"
include-in-header:
  - text: |
      <style>
      .reveal .slide-logo {
        max-height: unset;
        height: 100px;
      }
      </style>
footer: "Demystifying Causal Inference -  Lecture 4"
date: 05/28/2024
date-format: long
format: 
  revealjs:
    #theme: simple
    width: 1600
    height: 900
    transition: slide
    slide-number: c/t
    chalkboard: true
    auto-stretch: false
callout-appearance: minimal
---

# Outline {background-color="aquamarine"}

# Canonical setting {background-color="aquamarine"}

## Graphical representation

## Non-parametric asssumptions

## IV bounds

# Effect homogeneity {background-color="aquamarine"}

## Assumptions

## 2SLS

## Wald estimator

## Issues

# Modern IV {background-color="aquamarine"}

## LATE framework

Assuming effect heterogeneity, the estimand of interest is not the "total effect" anymore, but a new quantity:

. . . 

The Local Average Treatment Effect (LATE). Formally:

$$
E[\underbrace{Y_{d=1,i} - Y_{d=0,i}}_{\text{treatment effect}} \vert \underbrace{D_{z=1,i} \gt D_{z=0,i}}_{\text{among compliers}}]
$$

## Assumptions

### Relevance

$$
E[D_{z=1,i} - D_{z=0,i}] \neq 0
$$

## Assumptions

### Unconfoundedness of the instrument

$$
Y_{(d,z),i} \perp Z_i \forall d,z
$$

$$
D_{z,i} \perp Z_i \forall z
$$

## Assumptions

### Exclusion restriction

$$
Y_{(d,z),i} = Y_{(d,z'),i} = Y_{d,i} \forall z, z', d, i
$$


. . . 

:::callout-note
"Exclusion restriction" means that we can **exclude** the instrument $z$ from the outcome equation, once the treatment is accounted for
:::

## Assumptions
### Monotonicity

$$
D_{z=1,i} \geq D_{z=0,i} \forall i
$$

## Estimation

## Issues

# IV in practice {background-color="aquamarine"}


