---
title: "Practical 4: Instrumental variables"
format: html
---

(With Chad Hazlett)

In a well-known paper, Acemoglu, Johnson, and Robinson (2010) attempt to estimate the effect of property rights institutions on long-run economic growth. They use GDP per capita in 1995 to proxy a country's long-run economic growth. 

To address the endogeneity between institutions and economic growth, they use the mortality rate faced by European settlers in the 19th century as an instrument for property rights institutions in the 20th century. 

Here we will replicate the results from 2SLS regressions in the original paper (Table 4 Columns 1 and 2). Please download \texttt{arj.dta} from [here](). The data file include the following variables:

\bitem
\item \texttt{shortnam}: three letter country name
\item \texttt{lat\_abst}: absolute latitude of capital/90
\item \texttt{avexpr}: average protection against expropriation risks
\item \texttt{logpgp95}: log PPP GDP per capita in 1995
\item \texttt{logem4}: log settler mortality
\eitem

\bitem
\item[a)] Show results from (1) the first stage regression, (2) the reduced form regression, and (3) the 2SLS estimation using the following two specifications:
\begin{eqnarray*}
\texttt{logpgp95}_i &=& \beta_0 + \beta_1 \texttt{avexpr}_i + \epsilon_i \\
\texttt{avexpr}_i &=& \gamma_0 + \gamma_1 \texttt{logem4} + \mu_i 
\end{eqnarray*}
and 
\begin{eqnarray*}
\texttt{logpgp95}_i &=& \beta_0 + \beta_1 \texttt{avexpr}_i + \beta_3 \texttt{lat\_abst} + \epsilon_i\\
\texttt{avexpr}_i &=& \gamma_0 + \gamma_1 \texttt{logem4} + \gamma_2 \texttt{lat\_abst} + \mu_i
\end{eqnarray*}
